engine: elasticsearch

elasticsearch:
  url_env: ELASTICSEARCH_URL
  query_dump_directory: ./output

dataset: demo-hybrid

datasets:
  demo-hybrid:
    type: hybrid
    index_name: demo-hybrid
    schema_name: demo-hybrid-schema
    query_name: demo-hybrid-query
    vector_size: 384
    distance: cosine

    path:
      data_path: data/docs.ndjson
      queries_path: data/queries.ndjson

    data_mapping:
      id_field: id
      vector_field: embedding

    queries_mapping:
      query_text_field: query_text
      query_vector_field: embedding
      ground_truth_field: ground_truth

    param_groups:
      recall@10:
        - { size: 10, k: 10, num_candidates: 10, oversample: 1, rank: 10 }
        - { size: 10, k: 10, num_candidates: 20, oversample: 1, rank: 20 }
        - { size: 10, k: 10, num_candidates: 40, oversample: 1, rank: 40 }
        - { size: 10, k: 10, num_candidates: 80, oversample: 1, rank: 80 }
        - { size: 10, k: 10, num_candidates: 160, oversample: 1, rank: 160 }
        - { size: 10, k: 10, num_candidates: 320, oversample: 1, rank: 320 }
        - { size: 10, k: 10, num_candidates: 640, oversample: 1, rank: 640 }
        - { size: 10, k: 10, num_candidates: 1280, oversample: 1, rank: 1280 }
        - { size: 10, k: 10, num_candidates: 2560, oversample: 1, rank: 2560 }
      recall@50:
        - { size: 50, k: 50, num_candidates: 50, oversample: 1, rank: 50 }
        - { size: 50, k: 50, num_candidates: 80, oversample: 1, rank: 80 }
        - { size: 50, k: 50, num_candidates: 160, oversample: 1, rank: 160 }
        - { size: 50, k: 50, num_candidates: 320, oversample: 1, rank: 320 }
        - { size: 50, k: 50, num_candidates: 640, oversample: 1, rank: 640 }
        - { size: 50, k: 50, num_candidates: 1280, oversample: 1, rank: 1280 }
        - { size: 50, k: 50, num_candidates: 2560, oversample: 1, rank: 2560 }

load:
  threads: 4
  batch_size: 10
  queue_capacity: 10

evaluation:
  run_id: demo-hybrid
  warmup_workers: 1
  measurement_workers: 1
  warmup_rounds: 3
  measurement_rounds: 1

output:
  sinks:
    - type: elasticsearch
      config:
        url_env: SINK_URL
        index: jingra-results

analysis:
  run_id: demo-hybrid
  engines:
    - elasticsearch
  results_cluster:
    url_env: SINK_URL
    index: jingra-results
  output_directory: ./output
  generate_plots: true
  latency_metrics:
    - latency_median
    - latency_avg
