engine: mimir

mimir:
  url_env: MIMIR_URL
  org_id: anonymous

dataset:
  - avg_avgot_cpu_load_1m_filtered_by_hosts_5m

datasets:
  avg_avgot_cpu_load_1m_filtered_by_hosts_5m:
    type: metrics
    query_type: promql

    path:
      queries_path: data/avg_avgot_cpu_load_1m_filtered_by_hosts_5m-queries.ndjson

    data_mapping: {}

    queries_mapping:
      expected_rows_field: expected_rows

    param_groups:
      latency:
        - { query_name: avg_avgot_cpu_load_1m_filtered_by_hosts_5m }

load:
  await_index_ready: true
  metricsgen:
    version: 1.0.7
    scenario: builtin/hostmetrics
    scale: 100
    interval: 1s
    start_now_minus: 5m

evaluation:
  run_id: metrics-direct
  warmup_workers: 1
  measurement_workers: 1
  warmup_rounds: 3
  measurement_rounds: 5

output:
  sinks:
    - type: elasticsearch
      write_query_metrics: false
      config:
        url_env: SINK_URL
        index: jingra-results

analysis:
  run_id: metrics-direct
  engines:
    - mimir
  results_cluster:
    url_env: SINK_URL
    index: jingra-results
  output_directory: ./output
  generate_plots: true
  latency_metrics:
    - latency_median
    - latency_avg
