services:
  mimir:
    image: grafana/mimir:${MIMIR_VERSION}
    command:
      - '--config.file=/etc/mimir/mimir.yaml'
    volumes:
      - ${MIMIR_CONFIG_FILE}:/etc/mimir/mimir.yaml:ro
    ports:
      - "8080:8080"
    networks:
      - jingra-net

  jingra:
    environment:
      - MIMIR_URL=http://mimir:8080
    depends_on:
      mimir:
        condition: service_started
