engine: elasticsearch

elasticsearch:
  url_env: ELASTICSEARCH_URL
  query_dump_directory: ./output

dataset:
  - cpu-stats
  - disk-stats

datasets:
  cpu-stats:
    type: metrics
    query_type: esql
    index_name: metrics
    schema_name: metrics-schema

    path:
      data_path: data/docs.ndjson
      queries_path: data/cpu-stats-queries.ndjson

    data_mapping: {}

    queries_mapping:
      size_field: size
      expected_rows_field: expected_rows

    param_groups:
      latency@10:
        - { size: 10, query_name: cpu-stats }

  disk-stats:
    type: metrics
    query_type: esql
    index_name: metrics
    schema_name: metrics-schema

    path:
      data_path: data/docs.ndjson
      queries_path: data/disk-stats-queries.ndjson

    data_mapping: {}

    queries_mapping:
      size_field: size
      expected_rows_field: expected_rows

    param_groups:
      latency@10:
        - { size: 10, query_name: disk-stats }

load:
  threads: 4
  batch_size: 10
  queue_capacity: 10

evaluation:
  run_id: metrics
  warmup_workers: 1
  measurement_workers: 1
  warmup_rounds: 3
  measurement_rounds: 5

output:
  sinks:
    - type: elasticsearch
      write_query_metrics: false
      config:
        url_env: SINK_URL
        index: jingra-results

analysis:
  run_id: metrics
  engines:
    - elasticsearch
  results_cluster:
    url_env: SINK_URL
    index: jingra-results
  output_directory: ./output
  generate_plots: true
  latency_metrics:
    - latency_median
    - latency_avg
